# Web ContextRootPath and PortNumber Settings
server.servlet.context-path=/todaychef
server.port=8081
server.servlet.jsp.init-parameters.development=true
# DataBases
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=${TODAYCHEF_DB_URL:jdbc:postgresql://localhost:5432/todaychef}
spring.datasource.username=${TODAYCHEF_DB_USERNAME:postgres}
spring.datasource.password=${TODAYCHEF_DB_PASSWORD:}
# Mapper
mybatis.config-location=classpath:config/mybatis_config.xml
mybatis.mapper-locations=classpath:mapper/*.xml
# SQL init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
# Logging
logging.level.root=INFO
