# Local development profile
spring.datasource.url=${TODAYCHEF_DB_URL:jdbc:postgresql://localhost:5432/todaychef}
spring.datasource.username=${TODAYCHEF_DB_USERNAME:postgres}
spring.datasource.password=${TODAYCHEF_DB_PASSWORD}

# Run DB bootstrap scripts on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
